[project]
name = "game"
version = "0.1.0"
description = "Add a short description here"
authors = ["V <nandithebull@outlook.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
openai = "1.3.5.*"
python-dotenv = "1.0.0.*"
flask = "3.0.0.*"
